/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RandomOldArticlePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  cooldownDays: 365,
  excludedFolders: [],
  minFileAgeDays: 30
};
var RandomOldArticlePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.readHistory = {};
  }
  async onload() {
    await this.loadSettings();
    await this.loadHistory();
    this.addRibbonIcon("dice", "\u968F\u673A\u65E7\u6587\u7AE0", () => {
      this.pickRandomArticle();
    });
    this.addCommand({
      id: "pick-random-old-article",
      name: "\u6311\u9009\u968F\u673A\u65E7\u6587\u7AE0",
      callback: () => {
        this.pickRandomArticle();
      }
    });
    this.addSettingTab(new RandomOldArticleSettingTab(this.app, this));
    this.addCommand({
      id: "clear-read-history",
      name: "\u6E05\u9664\u9605\u8BFB\u5386\u53F2",
      callback: () => {
        this.clearHistory();
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...data };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadHistory() {
    const savedHistory = await this.loadData();
    if (savedHistory && savedHistory.history) {
      this.readHistory = savedHistory.history;
    }
  }
  async saveHistory() {
    const data = await this.loadData() || {};
    data.history = this.readHistory;
    await this.saveData(data);
  }
  async clearHistory() {
    this.readHistory = {};
    await this.saveHistory();
    new import_obsidian.Notice("\u9605\u8BFB\u5386\u53F2\u5DF2\u6E05\u9664");
  }
  async pickRandomArticle() {
    const files = await this.getEligibleFiles();
    if (files.length === 0) {
      new import_obsidian.Notice("\u6CA1\u6709\u627E\u5230\u7B26\u5408\u6761\u4EF6\u7684\u6587\u7AE0");
      return;
    }
    const randomIndex = Math.floor(Math.random() * files.length);
    const selectedFile = files[randomIndex];
    this.readHistory[selectedFile.path] = Date.now();
    await this.saveHistory();
    await this.app.workspace.openLinkText(selectedFile.path, "", false);
    const stats = this.getFileStats(selectedFile);
    new import_obsidian.Notice(`\u5DF2\u6253\u5F00: ${selectedFile.basename}
${stats}`, 5e3);
  }
  async getEligibleFiles() {
    const now = Date.now();
    const cooldownMs = this.settings.cooldownDays * 24 * 60 * 60 * 1e3;
    const minAgeMs = this.settings.minFileAgeDays * 24 * 60 * 60 * 1e3;
    const allFiles = this.app.vault.getMarkdownFiles();
    const eligibleFiles = [];
    for (const file of allFiles) {
      let excluded = false;
      for (const excludedFolder of this.settings.excludedFolders) {
        if (file.path.startsWith(excludedFolder)) {
          excluded = true;
          break;
        }
      }
      if (excluded)
        continue;
      const fileStat = await this.app.vault.adapter.stat(file.path);
      if (fileStat) {
        const fileAge = now - fileStat.ctime;
        if (fileAge < minAgeMs) {
          continue;
        }
      }
      const lastRead = this.readHistory[file.path];
      if (lastRead && now - lastRead < cooldownMs) {
        continue;
      }
      eligibleFiles.push(file);
    }
    return eligibleFiles;
  }
  getFileStats(file) {
    const lastRead = this.readHistory[file.path];
    if (lastRead) {
      const days = Math.floor((Date.now() - lastRead) / (24 * 60 * 60 * 1e3));
      return `\u4E0A\u6B21\u9605\u8BFB: ${days} \u5929\u524D`;
    }
    return "\u4ECE\u672A\u9605\u8BFB";
  }
};
var RandomOldArticleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  async display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u51B7\u5374\u671F\uFF08\u5929\uFF09").setDesc("\u6587\u7AE0\u88AB\u9605\u8BFB\u540E\uFF0C\u591A\u5C11\u5929\u5185\u4E0D\u4F1A\u518D\u88AB\u9009\u4E2D").addSlider((slider) => slider.setLimits(1, 730, 1).setValue(this.plugin.settings.cooldownDays).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.cooldownDays = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6700\u5C0F\u6587\u4EF6\u5E74\u9F84\uFF08\u5929\uFF09").setDesc("\u53EA\u9009\u62E9\u521B\u5EFA\u81F3\u5C11\u8FD9\u4E48\u591A\u5929\u7684\u6587\u7AE0").addSlider((slider) => slider.setLimits(0, 365, 1).setValue(this.plugin.settings.minFileAgeDays).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.minFileAgeDays = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u7684\u6587\u4EF6\u5939").setDesc("\u8F93\u5165\u8981\u6392\u9664\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF0C\u6BCF\u884C\u4E00\u4E2A").addTextArea((text) => text.setPlaceholder("\u4F8B\u5982\uFF1A\nTemplates\nDaily Notes\nArchive").setValue(this.plugin.settings.excludedFolders.join("\n")).onChange(async (value) => {
      this.plugin.settings.excludedFolders = value.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
      await this.plugin.saveSettings();
    }));
    const eligibleFiles = await this.plugin.getEligibleFiles();
    containerEl.createEl("h3", { text: "\u7EDF\u8BA1\u4FE1\u606F" });
    containerEl.createEl("p", {
      text: `\u7B26\u5408\u6761\u4EF6\u7684\u6587\u7AE0\u6570\u91CF: ${eligibleFiles.length}`
    });
    const historyCount = Object.keys(this.plugin.readHistory).length;
    containerEl.createEl("p", {
      text: `\u5DF2\u8BB0\u5F55\u7684\u5386\u53F2\u6587\u7AE0\u6570\u91CF: ${historyCount}`
    });
    new import_obsidian.Setting(containerEl).setName("\u6E05\u9664\u9605\u8BFB\u5386\u53F2").setDesc("\u91CD\u7F6E\u6240\u6709\u6587\u7AE0\u7684\u9605\u8BFB\u8BB0\u5F55").addButton((button) => button.setButtonText("\u6E05\u9664\u5386\u53F2").onClick(async () => {
      if (confirm("\u786E\u5B9A\u8981\u6E05\u9664\u6240\u6709\u9605\u8BFB\u5386\u53F2\u5417\uFF1F")) {
        await this.plugin.clearHistory();
        this.display();
      }
    }));
  }
};
